USE KinhDoanhTBMayTinh

--Tạo bảng Phòng ban
CREATE TABLE tblPhongBan (
	sMaPB VARCHAR(10) PRIMARY KEY ,
	sTenPB NVARCHAR(25) NOT NULL ,
)
-- Tạo bảng Nhân viên--
CREATE TABLE tblNhanVien (
	sMaNV VARCHAR(10) PRIMARY KEY ,
	sTenNV NVARCHAR(25) NOT NULL ,
	dNgaySinh DATE NOT NULL,
	sGioiTinh NVARCHAR(5) CHECK ( sGioiTinh IN ('Nam',N'Nữ')) ,
	sDiaChi NVARCHAR(50) NOT NULL ,
	sSDT VARCHAR(10) NOT NULL ,
	fHSL FLOAT CHECK(fHSL>=2 AND fHSL<=10) NOT NULL,
	fLCB FLOAT NOT NULL CHECK(fLCB>0),
	dNgayVaoLam DATE NOT NULL ,
	CONSTRAINT [Ngày vào làm đủ 18 tuổi] CHECK(DATEDIFF(DAY,dNgaySinh,dNgayVaoLam)/365>=18),
	sMaPB VARCHAR(10) CONSTRAINT FK_tblPhongBan FOREIGN KEY (sMaPB) REFERENCES tblPhongBan
	)

-- Tạo bảng khách hàng--
CREATE TABLE tblKhachHang(
	sMaKH VARCHAR(10) PRIMARY KEY NOT NULL,
	sTenKH NVARCHAR(25)  NOT NULL,
	sSDTKH VARCHAR(10),
	sEmail VARCHAR(50) ,
	sDiaChi NVARCHAR(50)
	)

-- Tạo bảng nhà cung cấp--
CREATE TABLE tblNhaCC(
	sMaNCC VARCHAR(10) PRIMARY KEY,
	sTenNCC VARCHAR(25),
	sDiaChiNCC NVARCHAR(50)
)

--Tạo bảng loại sản phẩm
CREATE TABLE tblLoaiSP(
	sMaLoai VARCHAR(10) PRIMARY KEY NOT NULL,
	sTenLoai NVARCHAR(50) NOT NULL
)

-- Tạo bảng sản phẩm--
CREATE TABLE tblSanPham(
	sMaSP VARCHAR(10) PRIMARY KEY NOT NULL,
	sMaLoai VARCHAR(10) CONSTRAINT FK_tblLoaiSP FOREIGN KEY (sMaLoai) REFERENCES tblLoaiSP,
	sHangSX NVARCHAR(25) NOT NULL,
	iNamSX INT NOT NULL,
	fDonGiaNhap FLOAT CHECK(fDonGiaNhap>0) NOT NULL,
	fDonGiaXuat FLOAT NOT NULL,
	CONSTRAINT dongia CHECK(fDonGiaXuat>fDonGiaNhap),
	);

-- Tạo bảng hoá đơn nhập --
CREATE TABLE tblHDNhap(
	sMaHDN VARCHAR(10) PRIMARY KEY,
	sMaNV VARCHAR(10) REFERENCES dbo.tblNhanVien(sMaNV) ON UPDATE CASCADE ON DELETE CASCADE ,
	dNgayNhap DATE CHECK(dNgayNhap<=GETDATE()) NOT NULL,
	sMaNCC VARCHAR(10) CONSTRAINT FK_tblNhaCC FOREIGN KEY (sMaNCC) REFERENCES tblNhaCC ON UPDATE CASCADE ON DELETE CASCADE
	)
ALTER TABLE tblHDNhap ADD iSoLuong INT NOT NULL CHECK (iSoLuong>0)

-- Tạo bảng chi tiết hoá đơn nhập--
CREATE TABLE tblCTNhap(
	sMaCTN VARCHAR(10) PRIMARY KEY NOT NULL,
	sMaHDN VARCHAR(10) REFERENCES tblHDNhap(sMaHDN) ON UPDATE CASCADE ON DELETE CASCADE  ,
	sMaSP VARCHAR(10)  REFERENCES dbo.tblSanPham(sMaSP) ON UPDATE CASCADE ON DELETE CASCADE,
	fDonGiaNhap FLOAT 
	)

-- Tạo bảng Hoá đơn xuất--
CREATE TABLE tblHDXuat(
	sMaHDX VARCHAR(10) PRIMARY KEY,
	sMaNV VARCHAR(10) REFERENCES tblNhanVien(sMaNV) ON UPDATE CASCADE ON DELETE CASCADE,
	dNgayLap DATE CHECK(dNgayLap<=GETDATE()) NOT NULL ,
	sMaKH VARCHAR(10) REFERENCES tblKhachHang(sMaKH) ON UPDATE CASCADE ON DELETE CASCADE ,
	sHinhThucTT NVARCHAR(20) NOT NULL CHECK(sHinhThucTT IN(N'Tiền mặt',N'Thẻ ngân hàng')),
	fTongtien FLOAT CHECK (fTongtien>0)
	)
ALTER TABLE tblHDXuat ADD iSoLuong INT NOT NULL CHECK (iSoLuong>0)

--Tạo bảng Bảo hành
CREATE TABLE tblBaoHanh(
	sMaBH VARCHAR(10) PRIMARY KEY NOT NULL,
	sMaSP VARCHAR(10) REFERENCES tblSanPham(sMaSP) ON UPDATE CASCADE ON DELETE CASCADE,
	sMaHDX VARCHAR(10) REFERENCES tblHDXuat(sMaHDX) ON UPDATE CASCADE ON DELETE CASCADE,
	sMaNV VARCHAR(10) REFERENCES tblNhanVien(sMaNV),
	sGhichu NVARCHAR(10)
)

-- Tạo bảng Chi tiết xuất--
CREATE TABLE tblCTXuat(
	sMaCTX VARCHAR(10) PRIMARY KEY NOT NULL,
	sMaHDX VARCHAR(10) REFERENCES tblHDXuat(sMaHDX) ON UPDATE CASCADE ON DELETE CASCADE ,
	sMaSP VARCHAR(10) REFERENCES tblSanPham (sMaSP) ON UPDATE CASCADE ON DELETE CASCADE ,
	fDonGiaXuat FLOAT 
	)